
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DALayer
{
	public abstract class _Categoria : SqlClientEntity
	{
		public _Categoria()
		{
			this.QuerySource = "Categoria";
			this.MappingName = "Categoria";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CategoriaLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id_categoria)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id_categoria, Id_categoria);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CategoriaLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id_categoria
			{
				get
				{
					return new SqlParameter("@Id_categoria", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Nombre_categoria
			{
				get
				{
					return new SqlParameter("@Nombre_categoria", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Descripcion
			{
				get
				{
					return new SqlParameter("@Descripcion", SqlDbType.VarChar, 150);
				}
			}
			
			public static SqlParameter Foto
			{
				get
				{
					return new SqlParameter("@Foto", SqlDbType.Image, 2147483647);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id_categoria = "id_categoria";
            public const string Nombre_categoria = "nombre_categoria";
            public const string Descripcion = "descripcion";
            public const string Foto = "foto";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id_categoria] = _Categoria.PropertyNames.Id_categoria;
					ht[Nombre_categoria] = _Categoria.PropertyNames.Nombre_categoria;
					ht[Descripcion] = _Categoria.PropertyNames.Descripcion;
					ht[Foto] = _Categoria.PropertyNames.Foto;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id_categoria = "Id_categoria";
            public const string Nombre_categoria = "Nombre_categoria";
            public const string Descripcion = "Descripcion";
            public const string Foto = "Foto";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id_categoria] = _Categoria.ColumnNames.Id_categoria;
					ht[Nombre_categoria] = _Categoria.ColumnNames.Nombre_categoria;
					ht[Descripcion] = _Categoria.ColumnNames.Descripcion;
					ht[Foto] = _Categoria.ColumnNames.Foto;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id_categoria = "s_Id_categoria";
            public const string Nombre_categoria = "s_Nombre_categoria";
            public const string Descripcion = "s_Descripcion";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id_categoria
	    {
			get
	        {
				return base.Getint(ColumnNames.Id_categoria);
			}
			set
	        {
				base.Setint(ColumnNames.Id_categoria, value);
			}
		}

		public virtual string Nombre_categoria
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nombre_categoria);
			}
			set
	        {
				base.Setstring(ColumnNames.Nombre_categoria, value);
			}
		}

		public virtual string Descripcion
	    {
			get
	        {
				return base.Getstring(ColumnNames.Descripcion);
			}
			set
	        {
				base.Setstring(ColumnNames.Descripcion, value);
			}
		}

		public virtual byte[] Foto
	    {
			get
	        {
				return base.GetByteArray(ColumnNames.Foto);
			}
			set
	        {
				base.SetByteArray(ColumnNames.Foto, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id_categoria
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id_categoria) ? string.Empty : base.GetintAsString(ColumnNames.Id_categoria);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id_categoria);
				else
					this.Id_categoria = base.SetintAsString(ColumnNames.Id_categoria, value);
			}
		}

		public virtual string s_Nombre_categoria
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nombre_categoria) ? string.Empty : base.GetstringAsString(ColumnNames.Nombre_categoria);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nombre_categoria);
				else
					this.Nombre_categoria = base.SetstringAsString(ColumnNames.Nombre_categoria, value);
			}
		}

		public virtual string s_Descripcion
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Descripcion) ? string.Empty : base.GetstringAsString(ColumnNames.Descripcion);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Descripcion);
				else
					this.Descripcion = base.SetstringAsString(ColumnNames.Descripcion, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id_categoria
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id_categoria, Parameters.Id_categoria);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nombre_categoria
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nombre_categoria, Parameters.Nombre_categoria);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Descripcion
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Descripcion, Parameters.Descripcion);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Foto
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Foto, Parameters.Foto);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id_categoria
		    {
				get
		        {
					if(_Id_categoria_W == null)
	        	    {
						_Id_categoria_W = TearOff.Id_categoria;
					}
					return _Id_categoria_W;
				}
			}

			public WhereParameter Nombre_categoria
		    {
				get
		        {
					if(_Nombre_categoria_W == null)
	        	    {
						_Nombre_categoria_W = TearOff.Nombre_categoria;
					}
					return _Nombre_categoria_W;
				}
			}

			public WhereParameter Descripcion
		    {
				get
		        {
					if(_Descripcion_W == null)
	        	    {
						_Descripcion_W = TearOff.Descripcion;
					}
					return _Descripcion_W;
				}
			}

			public WhereParameter Foto
		    {
				get
		        {
					if(_Foto_W == null)
	        	    {
						_Foto_W = TearOff.Foto;
					}
					return _Foto_W;
				}
			}

			private WhereParameter _Id_categoria_W = null;
			private WhereParameter _Nombre_categoria_W = null;
			private WhereParameter _Descripcion_W = null;
			private WhereParameter _Foto_W = null;

			public void WhereClauseReset()
			{
				_Id_categoria_W = null;
				_Nombre_categoria_W = null;
				_Descripcion_W = null;
				_Foto_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id_categoria
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id_categoria, Parameters.Id_categoria);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nombre_categoria
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nombre_categoria, Parameters.Nombre_categoria);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Descripcion
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Descripcion, Parameters.Descripcion);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Foto
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Foto, Parameters.Foto);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id_categoria
		    {
				get
		        {
					if(_Id_categoria_W == null)
	        	    {
						_Id_categoria_W = TearOff.Id_categoria;
					}
					return _Id_categoria_W;
				}
			}

			public AggregateParameter Nombre_categoria
		    {
				get
		        {
					if(_Nombre_categoria_W == null)
	        	    {
						_Nombre_categoria_W = TearOff.Nombre_categoria;
					}
					return _Nombre_categoria_W;
				}
			}

			public AggregateParameter Descripcion
		    {
				get
		        {
					if(_Descripcion_W == null)
	        	    {
						_Descripcion_W = TearOff.Descripcion;
					}
					return _Descripcion_W;
				}
			}

			public AggregateParameter Foto
		    {
				get
		        {
					if(_Foto_W == null)
	        	    {
						_Foto_W = TearOff.Foto;
					}
					return _Foto_W;
				}
			}

			private AggregateParameter _Id_categoria_W = null;
			private AggregateParameter _Nombre_categoria_W = null;
			private AggregateParameter _Descripcion_W = null;
			private AggregateParameter _Foto_W = null;

			public void AggregateClauseReset()
			{
				_Id_categoria_W = null;
				_Nombre_categoria_W = null;
				_Descripcion_W = null;
				_Foto_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CategoriaInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id_categoria.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CategoriaUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CategoriaDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id_categoria);
			p.SourceColumn = ColumnNames.Id_categoria;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id_categoria);
			p.SourceColumn = ColumnNames.Id_categoria;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Nombre_categoria);
			p.SourceColumn = ColumnNames.Nombre_categoria;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Descripcion);
			p.SourceColumn = ColumnNames.Descripcion;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Foto);
			p.SourceColumn = ColumnNames.Foto;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
