
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DALayer
{
	public abstract class _Producto_Orden : SqlClientEntity
	{
		public _Producto_Orden()
		{
			this.QuerySource = "Producto_Orden";
			this.MappingName = "Producto_Orden";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_Producto_OrdenLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id_producto, int Id_orden)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id_producto, Id_producto);

parameters.Add(Parameters.Id_orden, Id_orden);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_Producto_OrdenLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id_producto
			{
				get
				{
					return new SqlParameter("@Id_producto", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Id_orden
			{
				get
				{
					return new SqlParameter("@Id_orden", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Cantidad
			{
				get
				{
					return new SqlParameter("@Cantidad", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id_producto = "id_producto";
            public const string Id_orden = "id_orden";
            public const string Cantidad = "cantidad";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id_producto] = _Producto_Orden.PropertyNames.Id_producto;
					ht[Id_orden] = _Producto_Orden.PropertyNames.Id_orden;
					ht[Cantidad] = _Producto_Orden.PropertyNames.Cantidad;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id_producto = "Id_producto";
            public const string Id_orden = "Id_orden";
            public const string Cantidad = "Cantidad";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id_producto] = _Producto_Orden.ColumnNames.Id_producto;
					ht[Id_orden] = _Producto_Orden.ColumnNames.Id_orden;
					ht[Cantidad] = _Producto_Orden.ColumnNames.Cantidad;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id_producto = "s_Id_producto";
            public const string Id_orden = "s_Id_orden";
            public const string Cantidad = "s_Cantidad";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id_producto
	    {
			get
	        {
				return base.Getint(ColumnNames.Id_producto);
			}
			set
	        {
				base.Setint(ColumnNames.Id_producto, value);
			}
		}

		public virtual int Id_orden
	    {
			get
	        {
				return base.Getint(ColumnNames.Id_orden);
			}
			set
	        {
				base.Setint(ColumnNames.Id_orden, value);
			}
		}

		public virtual int Cantidad
	    {
			get
	        {
				return base.Getint(ColumnNames.Cantidad);
			}
			set
	        {
				base.Setint(ColumnNames.Cantidad, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id_producto
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id_producto) ? string.Empty : base.GetintAsString(ColumnNames.Id_producto);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id_producto);
				else
					this.Id_producto = base.SetintAsString(ColumnNames.Id_producto, value);
			}
		}

		public virtual string s_Id_orden
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id_orden) ? string.Empty : base.GetintAsString(ColumnNames.Id_orden);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id_orden);
				else
					this.Id_orden = base.SetintAsString(ColumnNames.Id_orden, value);
			}
		}

		public virtual string s_Cantidad
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Cantidad) ? string.Empty : base.GetintAsString(ColumnNames.Cantidad);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Cantidad);
				else
					this.Cantidad = base.SetintAsString(ColumnNames.Cantidad, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id_producto
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id_producto, Parameters.Id_producto);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Id_orden
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id_orden, Parameters.Id_orden);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Cantidad
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Cantidad, Parameters.Cantidad);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id_producto
		    {
				get
		        {
					if(_Id_producto_W == null)
	        	    {
						_Id_producto_W = TearOff.Id_producto;
					}
					return _Id_producto_W;
				}
			}

			public WhereParameter Id_orden
		    {
				get
		        {
					if(_Id_orden_W == null)
	        	    {
						_Id_orden_W = TearOff.Id_orden;
					}
					return _Id_orden_W;
				}
			}

			public WhereParameter Cantidad
		    {
				get
		        {
					if(_Cantidad_W == null)
	        	    {
						_Cantidad_W = TearOff.Cantidad;
					}
					return _Cantidad_W;
				}
			}

			private WhereParameter _Id_producto_W = null;
			private WhereParameter _Id_orden_W = null;
			private WhereParameter _Cantidad_W = null;

			public void WhereClauseReset()
			{
				_Id_producto_W = null;
				_Id_orden_W = null;
				_Cantidad_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id_producto
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id_producto, Parameters.Id_producto);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Id_orden
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id_orden, Parameters.Id_orden);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Cantidad
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Cantidad, Parameters.Cantidad);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id_producto
		    {
				get
		        {
					if(_Id_producto_W == null)
	        	    {
						_Id_producto_W = TearOff.Id_producto;
					}
					return _Id_producto_W;
				}
			}

			public AggregateParameter Id_orden
		    {
				get
		        {
					if(_Id_orden_W == null)
	        	    {
						_Id_orden_W = TearOff.Id_orden;
					}
					return _Id_orden_W;
				}
			}

			public AggregateParameter Cantidad
		    {
				get
		        {
					if(_Cantidad_W == null)
	        	    {
						_Cantidad_W = TearOff.Cantidad;
					}
					return _Cantidad_W;
				}
			}

			private AggregateParameter _Id_producto_W = null;
			private AggregateParameter _Id_orden_W = null;
			private AggregateParameter _Cantidad_W = null;

			public void AggregateClauseReset()
			{
				_Id_producto_W = null;
				_Id_orden_W = null;
				_Cantidad_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_Producto_OrdenInsert]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_Producto_OrdenUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_Producto_OrdenDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id_producto);
			p.SourceColumn = ColumnNames.Id_producto;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Id_orden);
			p.SourceColumn = ColumnNames.Id_orden;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id_producto);
			p.SourceColumn = ColumnNames.Id_producto;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Id_orden);
			p.SourceColumn = ColumnNames.Id_orden;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Cantidad);
			p.SourceColumn = ColumnNames.Cantidad;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
