
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DALayer
{
	public abstract class _Role : SqlClientEntity
	{
		public _Role()
		{
			this.QuerySource = "Role";
			this.MappingName = "Role";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_RoleLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id_role)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id_role, Id_role);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_RoleLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id_role
			{
				get
				{
					return new SqlParameter("@Id_role", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Nombre_role
			{
				get
				{
					return new SqlParameter("@Nombre_role", SqlDbType.VarChar, 50);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id_role = "id_role";
            public const string Nombre_role = "nombre_role";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id_role] = _Role.PropertyNames.Id_role;
					ht[Nombre_role] = _Role.PropertyNames.Nombre_role;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id_role = "Id_role";
            public const string Nombre_role = "Nombre_role";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id_role] = _Role.ColumnNames.Id_role;
					ht[Nombre_role] = _Role.ColumnNames.Nombre_role;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id_role = "s_Id_role";
            public const string Nombre_role = "s_Nombre_role";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id_role
	    {
			get
	        {
				return base.Getint(ColumnNames.Id_role);
			}
			set
	        {
				base.Setint(ColumnNames.Id_role, value);
			}
		}

		public virtual string Nombre_role
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nombre_role);
			}
			set
	        {
				base.Setstring(ColumnNames.Nombre_role, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id_role
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id_role) ? string.Empty : base.GetintAsString(ColumnNames.Id_role);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id_role);
				else
					this.Id_role = base.SetintAsString(ColumnNames.Id_role, value);
			}
		}

		public virtual string s_Nombre_role
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nombre_role) ? string.Empty : base.GetstringAsString(ColumnNames.Nombre_role);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nombre_role);
				else
					this.Nombre_role = base.SetstringAsString(ColumnNames.Nombre_role, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id_role
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id_role, Parameters.Id_role);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nombre_role
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nombre_role, Parameters.Nombre_role);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id_role
		    {
				get
		        {
					if(_Id_role_W == null)
	        	    {
						_Id_role_W = TearOff.Id_role;
					}
					return _Id_role_W;
				}
			}

			public WhereParameter Nombre_role
		    {
				get
		        {
					if(_Nombre_role_W == null)
	        	    {
						_Nombre_role_W = TearOff.Nombre_role;
					}
					return _Nombre_role_W;
				}
			}

			private WhereParameter _Id_role_W = null;
			private WhereParameter _Nombre_role_W = null;

			public void WhereClauseReset()
			{
				_Id_role_W = null;
				_Nombre_role_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id_role
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id_role, Parameters.Id_role);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nombre_role
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nombre_role, Parameters.Nombre_role);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id_role
		    {
				get
		        {
					if(_Id_role_W == null)
	        	    {
						_Id_role_W = TearOff.Id_role;
					}
					return _Id_role_W;
				}
			}

			public AggregateParameter Nombre_role
		    {
				get
		        {
					if(_Nombre_role_W == null)
	        	    {
						_Nombre_role_W = TearOff.Nombre_role;
					}
					return _Nombre_role_W;
				}
			}

			private AggregateParameter _Id_role_W = null;
			private AggregateParameter _Nombre_role_W = null;

			public void AggregateClauseReset()
			{
				_Id_role_W = null;
				_Nombre_role_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RoleInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id_role.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RoleUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RoleDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id_role);
			p.SourceColumn = ColumnNames.Id_role;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id_role);
			p.SourceColumn = ColumnNames.Id_role;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Nombre_role);
			p.SourceColumn = ColumnNames.Nombre_role;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
