/*
'===============================================================================
'  Generated From - CSharp_dOOdads_View.vbgen
'
'  The supporting base class SqlClientEntity is in the 
'  Architecture directory in "dOOdads".
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DALayer
{
	public class _Orden_Productos_Carro : SqlClientEntity
	{
		public _Orden_Productos_Carro()
		{
			this.QuerySource = "_Orden_Productos_Carro";
			this.MappingName = "_Orden_Productos_Carro";
		}	
	
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			return base.Query.Load();
		}
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
	
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Nombre_proveedor
			{
				get
				{
					return new SqlParameter("@Nombre_proveedor", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Cantidad
			{
				get
				{
					return new SqlParameter("@Cantidad", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Id_orden
			{
				get
				{
					return new SqlParameter("@Id_orden", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Id_producto
			{
				get
				{
					return new SqlParameter("@Id_producto", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Codigo
			{
				get
				{
					return new SqlParameter("@Codigo", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Nombre_producto
			{
				get
				{
					return new SqlParameter("@Nombre_producto", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Precio
			{
				get
				{
					return new SqlParameter("@Precio", SqlDbType.Money, 0);
				}
			}
			
			public static SqlParameter Marca
			{
				get
				{
					return new SqlParameter("@Marca", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Nombre_distribuidor
			{
				get
				{
					return new SqlParameter("@Nombre_distribuidor", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Nombre_envio
			{
				get
				{
					return new SqlParameter("@Nombre_envio", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Nombre_estado
			{
				get
				{
					return new SqlParameter("@Nombre_estado", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter No_orden
			{
				get
				{
					return new SqlParameter("@No_orden", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Fecha
			{
				get
				{
					return new SqlParameter("@Fecha", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter Direccion_entrega
			{
				get
				{
					return new SqlParameter("@Direccion_entrega", SqlDbType.VarChar, 500);
				}
			}
			
			public static SqlParameter Comentario
			{
				get
				{
					return new SqlParameter("@Comentario", SqlDbType.VarChar, 1000);
				}
			}
			
			public static SqlParameter Telefono
			{
				get
				{
					return new SqlParameter("@Telefono", SqlDbType.VarChar, 20);
				}
			}
			
			public static SqlParameter Email_notificacion
			{
				get
				{
					return new SqlParameter("@Email_notificacion", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Destinatario
			{
				get
				{
					return new SqlParameter("@Destinatario", SqlDbType.VarChar, 50);
				}
			}
			
		}
		#endregion	
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Nombre_proveedor = "nombre_proveedor";
            public const string Cantidad = "cantidad";
            public const string Id_orden = "id_orden";
            public const string Id_producto = "id_producto";
            public const string Codigo = "codigo";
            public const string Nombre_producto = "nombre_producto";
            public const string Precio = "precio";
            public const string Marca = "marca";
            public const string Nombre_distribuidor = "nombre_distribuidor";
            public const string Nombre_envio = "nombre_envio";
            public const string Nombre_estado = "nombre_estado";
            public const string No_orden = "no_orden";
            public const string Fecha = "fecha";
            public const string Direccion_entrega = "direccion_entrega";
            public const string Comentario = "comentario";
            public const string Telefono = "telefono";
            public const string Email_notificacion = "email_notificacion";
            public const string Destinatario = "destinatario";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Nombre_proveedor] = _Orden_Productos_Carro.PropertyNames.Nombre_proveedor;
					ht[Cantidad] = _Orden_Productos_Carro.PropertyNames.Cantidad;
					ht[Id_orden] = _Orden_Productos_Carro.PropertyNames.Id_orden;
					ht[Id_producto] = _Orden_Productos_Carro.PropertyNames.Id_producto;
					ht[Codigo] = _Orden_Productos_Carro.PropertyNames.Codigo;
					ht[Nombre_producto] = _Orden_Productos_Carro.PropertyNames.Nombre_producto;
					ht[Precio] = _Orden_Productos_Carro.PropertyNames.Precio;
					ht[Marca] = _Orden_Productos_Carro.PropertyNames.Marca;
					ht[Nombre_distribuidor] = _Orden_Productos_Carro.PropertyNames.Nombre_distribuidor;
					ht[Nombre_envio] = _Orden_Productos_Carro.PropertyNames.Nombre_envio;
					ht[Nombre_estado] = _Orden_Productos_Carro.PropertyNames.Nombre_estado;
					ht[No_orden] = _Orden_Productos_Carro.PropertyNames.No_orden;
					ht[Fecha] = _Orden_Productos_Carro.PropertyNames.Fecha;
					ht[Direccion_entrega] = _Orden_Productos_Carro.PropertyNames.Direccion_entrega;
					ht[Comentario] = _Orden_Productos_Carro.PropertyNames.Comentario;
					ht[Telefono] = _Orden_Productos_Carro.PropertyNames.Telefono;
					ht[Email_notificacion] = _Orden_Productos_Carro.PropertyNames.Email_notificacion;
					ht[Destinatario] = _Orden_Productos_Carro.PropertyNames.Destinatario;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Nombre_proveedor = "Nombre_proveedor";
            public const string Cantidad = "Cantidad";
            public const string Id_orden = "Id_orden";
            public const string Id_producto = "Id_producto";
            public const string Codigo = "Codigo";
            public const string Nombre_producto = "Nombre_producto";
            public const string Precio = "Precio";
            public const string Marca = "Marca";
            public const string Nombre_distribuidor = "Nombre_distribuidor";
            public const string Nombre_envio = "Nombre_envio";
            public const string Nombre_estado = "Nombre_estado";
            public const string No_orden = "No_orden";
            public const string Fecha = "Fecha";
            public const string Direccion_entrega = "Direccion_entrega";
            public const string Comentario = "Comentario";
            public const string Telefono = "Telefono";
            public const string Email_notificacion = "Email_notificacion";
            public const string Destinatario = "Destinatario";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Nombre_proveedor] = _Orden_Productos_Carro.ColumnNames.Nombre_proveedor;
					ht[Cantidad] = _Orden_Productos_Carro.ColumnNames.Cantidad;
					ht[Id_orden] = _Orden_Productos_Carro.ColumnNames.Id_orden;
					ht[Id_producto] = _Orden_Productos_Carro.ColumnNames.Id_producto;
					ht[Codigo] = _Orden_Productos_Carro.ColumnNames.Codigo;
					ht[Nombre_producto] = _Orden_Productos_Carro.ColumnNames.Nombre_producto;
					ht[Precio] = _Orden_Productos_Carro.ColumnNames.Precio;
					ht[Marca] = _Orden_Productos_Carro.ColumnNames.Marca;
					ht[Nombre_distribuidor] = _Orden_Productos_Carro.ColumnNames.Nombre_distribuidor;
					ht[Nombre_envio] = _Orden_Productos_Carro.ColumnNames.Nombre_envio;
					ht[Nombre_estado] = _Orden_Productos_Carro.ColumnNames.Nombre_estado;
					ht[No_orden] = _Orden_Productos_Carro.ColumnNames.No_orden;
					ht[Fecha] = _Orden_Productos_Carro.ColumnNames.Fecha;
					ht[Direccion_entrega] = _Orden_Productos_Carro.ColumnNames.Direccion_entrega;
					ht[Comentario] = _Orden_Productos_Carro.ColumnNames.Comentario;
					ht[Telefono] = _Orden_Productos_Carro.ColumnNames.Telefono;
					ht[Email_notificacion] = _Orden_Productos_Carro.ColumnNames.Email_notificacion;
					ht[Destinatario] = _Orden_Productos_Carro.ColumnNames.Destinatario;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Nombre_proveedor = "s_Nombre_proveedor";
            public const string Cantidad = "s_Cantidad";
            public const string Id_orden = "s_Id_orden";
            public const string Id_producto = "s_Id_producto";
            public const string Codigo = "s_Codigo";
            public const string Nombre_producto = "s_Nombre_producto";
            public const string Precio = "s_Precio";
            public const string Marca = "s_Marca";
            public const string Nombre_distribuidor = "s_Nombre_distribuidor";
            public const string Nombre_envio = "s_Nombre_envio";
            public const string Nombre_estado = "s_Nombre_estado";
            public const string No_orden = "s_No_orden";
            public const string Fecha = "s_Fecha";
            public const string Direccion_entrega = "s_Direccion_entrega";
            public const string Comentario = "s_Comentario";
            public const string Telefono = "s_Telefono";
            public const string Email_notificacion = "s_Email_notificacion";
            public const string Destinatario = "s_Destinatario";

		}
		#endregion	
		
		#region Properties
			public virtual string Nombre_proveedor
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nombre_proveedor);
			}
			set
	        {
				base.Setstring(ColumnNames.Nombre_proveedor, value);
			}
		}

		public virtual int Cantidad
	    {
			get
	        {
				return base.Getint(ColumnNames.Cantidad);
			}
			set
	        {
				base.Setint(ColumnNames.Cantidad, value);
			}
		}

		public virtual int Id_orden
	    {
			get
	        {
				return base.Getint(ColumnNames.Id_orden);
			}
			set
	        {
				base.Setint(ColumnNames.Id_orden, value);
			}
		}

		public virtual int Id_producto
	    {
			get
	        {
				return base.Getint(ColumnNames.Id_producto);
			}
			set
	        {
				base.Setint(ColumnNames.Id_producto, value);
			}
		}

		public virtual string Codigo
	    {
			get
	        {
				return base.Getstring(ColumnNames.Codigo);
			}
			set
	        {
				base.Setstring(ColumnNames.Codigo, value);
			}
		}

		public virtual string Nombre_producto
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nombre_producto);
			}
			set
	        {
				base.Setstring(ColumnNames.Nombre_producto, value);
			}
		}

		public virtual decimal Precio
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.Precio);
			}
			set
	        {
				base.Setdecimal(ColumnNames.Precio, value);
			}
		}

		public virtual string Marca
	    {
			get
	        {
				return base.Getstring(ColumnNames.Marca);
			}
			set
	        {
				base.Setstring(ColumnNames.Marca, value);
			}
		}

		public virtual string Nombre_distribuidor
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nombre_distribuidor);
			}
			set
	        {
				base.Setstring(ColumnNames.Nombre_distribuidor, value);
			}
		}

		public virtual string Nombre_envio
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nombre_envio);
			}
			set
	        {
				base.Setstring(ColumnNames.Nombre_envio, value);
			}
		}

		public virtual string Nombre_estado
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nombre_estado);
			}
			set
	        {
				base.Setstring(ColumnNames.Nombre_estado, value);
			}
		}

		public virtual int No_orden
	    {
			get
	        {
				return base.Getint(ColumnNames.No_orden);
			}
			set
	        {
				base.Setint(ColumnNames.No_orden, value);
			}
		}

		public virtual DateTime Fecha
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.Fecha);
			}
			set
	        {
				base.SetDateTime(ColumnNames.Fecha, value);
			}
		}

		public virtual string Direccion_entrega
	    {
			get
	        {
				return base.Getstring(ColumnNames.Direccion_entrega);
			}
			set
	        {
				base.Setstring(ColumnNames.Direccion_entrega, value);
			}
		}

		public virtual string Comentario
	    {
			get
	        {
				return base.Getstring(ColumnNames.Comentario);
			}
			set
	        {
				base.Setstring(ColumnNames.Comentario, value);
			}
		}

		public virtual string Telefono
	    {
			get
	        {
				return base.Getstring(ColumnNames.Telefono);
			}
			set
	        {
				base.Setstring(ColumnNames.Telefono, value);
			}
		}

		public virtual string Email_notificacion
	    {
			get
	        {
				return base.Getstring(ColumnNames.Email_notificacion);
			}
			set
	        {
				base.Setstring(ColumnNames.Email_notificacion, value);
			}
		}

		public virtual string Destinatario
	    {
			get
	        {
				return base.Getstring(ColumnNames.Destinatario);
			}
			set
	        {
				base.Setstring(ColumnNames.Destinatario, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Nombre_proveedor
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nombre_proveedor) ? string.Empty : base.GetstringAsString(ColumnNames.Nombre_proveedor);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nombre_proveedor);
				else
					this.Nombre_proveedor = base.SetstringAsString(ColumnNames.Nombre_proveedor, value);
			}
		}

		public virtual string s_Cantidad
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Cantidad) ? string.Empty : base.GetintAsString(ColumnNames.Cantidad);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Cantidad);
				else
					this.Cantidad = base.SetintAsString(ColumnNames.Cantidad, value);
			}
		}

		public virtual string s_Id_orden
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id_orden) ? string.Empty : base.GetintAsString(ColumnNames.Id_orden);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id_orden);
				else
					this.Id_orden = base.SetintAsString(ColumnNames.Id_orden, value);
			}
		}

		public virtual string s_Id_producto
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id_producto) ? string.Empty : base.GetintAsString(ColumnNames.Id_producto);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id_producto);
				else
					this.Id_producto = base.SetintAsString(ColumnNames.Id_producto, value);
			}
		}

		public virtual string s_Codigo
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Codigo) ? string.Empty : base.GetstringAsString(ColumnNames.Codigo);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Codigo);
				else
					this.Codigo = base.SetstringAsString(ColumnNames.Codigo, value);
			}
		}

		public virtual string s_Nombre_producto
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nombre_producto) ? string.Empty : base.GetstringAsString(ColumnNames.Nombre_producto);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nombre_producto);
				else
					this.Nombre_producto = base.SetstringAsString(ColumnNames.Nombre_producto, value);
			}
		}

		public virtual string s_Precio
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Precio) ? string.Empty : base.GetdecimalAsString(ColumnNames.Precio);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Precio);
				else
					this.Precio = base.SetdecimalAsString(ColumnNames.Precio, value);
			}
		}

		public virtual string s_Marca
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Marca) ? string.Empty : base.GetstringAsString(ColumnNames.Marca);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Marca);
				else
					this.Marca = base.SetstringAsString(ColumnNames.Marca, value);
			}
		}

		public virtual string s_Nombre_distribuidor
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nombre_distribuidor) ? string.Empty : base.GetstringAsString(ColumnNames.Nombre_distribuidor);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nombre_distribuidor);
				else
					this.Nombre_distribuidor = base.SetstringAsString(ColumnNames.Nombre_distribuidor, value);
			}
		}

		public virtual string s_Nombre_envio
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nombre_envio) ? string.Empty : base.GetstringAsString(ColumnNames.Nombre_envio);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nombre_envio);
				else
					this.Nombre_envio = base.SetstringAsString(ColumnNames.Nombre_envio, value);
			}
		}

		public virtual string s_Nombre_estado
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nombre_estado) ? string.Empty : base.GetstringAsString(ColumnNames.Nombre_estado);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nombre_estado);
				else
					this.Nombre_estado = base.SetstringAsString(ColumnNames.Nombre_estado, value);
			}
		}

		public virtual string s_No_orden
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.No_orden) ? string.Empty : base.GetintAsString(ColumnNames.No_orden);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.No_orden);
				else
					this.No_orden = base.SetintAsString(ColumnNames.No_orden, value);
			}
		}

		public virtual string s_Fecha
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Fecha) ? string.Empty : base.GetDateTimeAsString(ColumnNames.Fecha);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Fecha);
				else
					this.Fecha = base.SetDateTimeAsString(ColumnNames.Fecha, value);
			}
		}

		public virtual string s_Direccion_entrega
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Direccion_entrega) ? string.Empty : base.GetstringAsString(ColumnNames.Direccion_entrega);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Direccion_entrega);
				else
					this.Direccion_entrega = base.SetstringAsString(ColumnNames.Direccion_entrega, value);
			}
		}

		public virtual string s_Comentario
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Comentario) ? string.Empty : base.GetstringAsString(ColumnNames.Comentario);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Comentario);
				else
					this.Comentario = base.SetstringAsString(ColumnNames.Comentario, value);
			}
		}

		public virtual string s_Telefono
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Telefono) ? string.Empty : base.GetstringAsString(ColumnNames.Telefono);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Telefono);
				else
					this.Telefono = base.SetstringAsString(ColumnNames.Telefono, value);
			}
		}

		public virtual string s_Email_notificacion
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Email_notificacion) ? string.Empty : base.GetstringAsString(ColumnNames.Email_notificacion);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Email_notificacion);
				else
					this.Email_notificacion = base.SetstringAsString(ColumnNames.Email_notificacion, value);
			}
		}

		public virtual string s_Destinatario
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Destinatario) ? string.Empty : base.GetstringAsString(ColumnNames.Destinatario);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Destinatario);
				else
					this.Destinatario = base.SetstringAsString(ColumnNames.Destinatario, value);
			}
		}


		#endregion			
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Nombre_proveedor
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nombre_proveedor, Parameters.Nombre_proveedor);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Cantidad
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Cantidad, Parameters.Cantidad);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Id_orden
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id_orden, Parameters.Id_orden);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Id_producto
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id_producto, Parameters.Id_producto);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Codigo
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Codigo, Parameters.Codigo);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nombre_producto
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nombre_producto, Parameters.Nombre_producto);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Precio
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Precio, Parameters.Precio);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Marca
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Marca, Parameters.Marca);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nombre_distribuidor
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nombre_distribuidor, Parameters.Nombre_distribuidor);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nombre_envio
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nombre_envio, Parameters.Nombre_envio);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nombre_estado
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nombre_estado, Parameters.Nombre_estado);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter No_orden
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.No_orden, Parameters.No_orden);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Fecha
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Fecha, Parameters.Fecha);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Direccion_entrega
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Direccion_entrega, Parameters.Direccion_entrega);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Comentario
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Comentario, Parameters.Comentario);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Telefono
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Telefono, Parameters.Telefono);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Email_notificacion
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Email_notificacion, Parameters.Email_notificacion);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Destinatario
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Destinatario, Parameters.Destinatario);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Nombre_proveedor
		    {
				get
		        {
					if(_Nombre_proveedor_W == null)
	        	    {
						_Nombre_proveedor_W = TearOff.Nombre_proveedor;
					}
					return _Nombre_proveedor_W;
				}
			}

			public WhereParameter Cantidad
		    {
				get
		        {
					if(_Cantidad_W == null)
	        	    {
						_Cantidad_W = TearOff.Cantidad;
					}
					return _Cantidad_W;
				}
			}

			public WhereParameter Id_orden
		    {
				get
		        {
					if(_Id_orden_W == null)
	        	    {
						_Id_orden_W = TearOff.Id_orden;
					}
					return _Id_orden_W;
				}
			}

			public WhereParameter Id_producto
		    {
				get
		        {
					if(_Id_producto_W == null)
	        	    {
						_Id_producto_W = TearOff.Id_producto;
					}
					return _Id_producto_W;
				}
			}

			public WhereParameter Codigo
		    {
				get
		        {
					if(_Codigo_W == null)
	        	    {
						_Codigo_W = TearOff.Codigo;
					}
					return _Codigo_W;
				}
			}

			public WhereParameter Nombre_producto
		    {
				get
		        {
					if(_Nombre_producto_W == null)
	        	    {
						_Nombre_producto_W = TearOff.Nombre_producto;
					}
					return _Nombre_producto_W;
				}
			}

			public WhereParameter Precio
		    {
				get
		        {
					if(_Precio_W == null)
	        	    {
						_Precio_W = TearOff.Precio;
					}
					return _Precio_W;
				}
			}

			public WhereParameter Marca
		    {
				get
		        {
					if(_Marca_W == null)
	        	    {
						_Marca_W = TearOff.Marca;
					}
					return _Marca_W;
				}
			}

			public WhereParameter Nombre_distribuidor
		    {
				get
		        {
					if(_Nombre_distribuidor_W == null)
	        	    {
						_Nombre_distribuidor_W = TearOff.Nombre_distribuidor;
					}
					return _Nombre_distribuidor_W;
				}
			}

			public WhereParameter Nombre_envio
		    {
				get
		        {
					if(_Nombre_envio_W == null)
	        	    {
						_Nombre_envio_W = TearOff.Nombre_envio;
					}
					return _Nombre_envio_W;
				}
			}

			public WhereParameter Nombre_estado
		    {
				get
		        {
					if(_Nombre_estado_W == null)
	        	    {
						_Nombre_estado_W = TearOff.Nombre_estado;
					}
					return _Nombre_estado_W;
				}
			}

			public WhereParameter No_orden
		    {
				get
		        {
					if(_No_orden_W == null)
	        	    {
						_No_orden_W = TearOff.No_orden;
					}
					return _No_orden_W;
				}
			}

			public WhereParameter Fecha
		    {
				get
		        {
					if(_Fecha_W == null)
	        	    {
						_Fecha_W = TearOff.Fecha;
					}
					return _Fecha_W;
				}
			}

			public WhereParameter Direccion_entrega
		    {
				get
		        {
					if(_Direccion_entrega_W == null)
	        	    {
						_Direccion_entrega_W = TearOff.Direccion_entrega;
					}
					return _Direccion_entrega_W;
				}
			}

			public WhereParameter Comentario
		    {
				get
		        {
					if(_Comentario_W == null)
	        	    {
						_Comentario_W = TearOff.Comentario;
					}
					return _Comentario_W;
				}
			}

			public WhereParameter Telefono
		    {
				get
		        {
					if(_Telefono_W == null)
	        	    {
						_Telefono_W = TearOff.Telefono;
					}
					return _Telefono_W;
				}
			}

			public WhereParameter Email_notificacion
		    {
				get
		        {
					if(_Email_notificacion_W == null)
	        	    {
						_Email_notificacion_W = TearOff.Email_notificacion;
					}
					return _Email_notificacion_W;
				}
			}

			public WhereParameter Destinatario
		    {
				get
		        {
					if(_Destinatario_W == null)
	        	    {
						_Destinatario_W = TearOff.Destinatario;
					}
					return _Destinatario_W;
				}
			}

			private WhereParameter _Nombre_proveedor_W = null;
			private WhereParameter _Cantidad_W = null;
			private WhereParameter _Id_orden_W = null;
			private WhereParameter _Id_producto_W = null;
			private WhereParameter _Codigo_W = null;
			private WhereParameter _Nombre_producto_W = null;
			private WhereParameter _Precio_W = null;
			private WhereParameter _Marca_W = null;
			private WhereParameter _Nombre_distribuidor_W = null;
			private WhereParameter _Nombre_envio_W = null;
			private WhereParameter _Nombre_estado_W = null;
			private WhereParameter _No_orden_W = null;
			private WhereParameter _Fecha_W = null;
			private WhereParameter _Direccion_entrega_W = null;
			private WhereParameter _Comentario_W = null;
			private WhereParameter _Telefono_W = null;
			private WhereParameter _Email_notificacion_W = null;
			private WhereParameter _Destinatario_W = null;

			public void WhereClauseReset()
			{
				_Nombre_proveedor_W = null;
				_Cantidad_W = null;
				_Id_orden_W = null;
				_Id_producto_W = null;
				_Codigo_W = null;
				_Nombre_producto_W = null;
				_Precio_W = null;
				_Marca_W = null;
				_Nombre_distribuidor_W = null;
				_Nombre_envio_W = null;
				_Nombre_estado_W = null;
				_No_orden_W = null;
				_Fecha_W = null;
				_Direccion_entrega_W = null;
				_Comentario_W = null;
				_Telefono_W = null;
				_Email_notificacion_W = null;
				_Destinatario_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Nombre_proveedor
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nombre_proveedor, Parameters.Nombre_proveedor);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Cantidad
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Cantidad, Parameters.Cantidad);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Id_orden
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id_orden, Parameters.Id_orden);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Id_producto
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id_producto, Parameters.Id_producto);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Codigo
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Codigo, Parameters.Codigo);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nombre_producto
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nombre_producto, Parameters.Nombre_producto);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Precio
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Precio, Parameters.Precio);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Marca
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Marca, Parameters.Marca);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nombre_distribuidor
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nombre_distribuidor, Parameters.Nombre_distribuidor);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nombre_envio
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nombre_envio, Parameters.Nombre_envio);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nombre_estado
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nombre_estado, Parameters.Nombre_estado);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter No_orden
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.No_orden, Parameters.No_orden);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Fecha
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Fecha, Parameters.Fecha);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Direccion_entrega
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Direccion_entrega, Parameters.Direccion_entrega);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Comentario
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Comentario, Parameters.Comentario);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Telefono
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Telefono, Parameters.Telefono);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Email_notificacion
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Email_notificacion, Parameters.Email_notificacion);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Destinatario
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Destinatario, Parameters.Destinatario);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Nombre_proveedor
		    {
				get
		        {
					if(_Nombre_proveedor_W == null)
	        	    {
						_Nombre_proveedor_W = TearOff.Nombre_proveedor;
					}
					return _Nombre_proveedor_W;
				}
			}

			public AggregateParameter Cantidad
		    {
				get
		        {
					if(_Cantidad_W == null)
	        	    {
						_Cantidad_W = TearOff.Cantidad;
					}
					return _Cantidad_W;
				}
			}

			public AggregateParameter Id_orden
		    {
				get
		        {
					if(_Id_orden_W == null)
	        	    {
						_Id_orden_W = TearOff.Id_orden;
					}
					return _Id_orden_W;
				}
			}

			public AggregateParameter Id_producto
		    {
				get
		        {
					if(_Id_producto_W == null)
	        	    {
						_Id_producto_W = TearOff.Id_producto;
					}
					return _Id_producto_W;
				}
			}

			public AggregateParameter Codigo
		    {
				get
		        {
					if(_Codigo_W == null)
	        	    {
						_Codigo_W = TearOff.Codigo;
					}
					return _Codigo_W;
				}
			}

			public AggregateParameter Nombre_producto
		    {
				get
		        {
					if(_Nombre_producto_W == null)
	        	    {
						_Nombre_producto_W = TearOff.Nombre_producto;
					}
					return _Nombre_producto_W;
				}
			}

			public AggregateParameter Precio
		    {
				get
		        {
					if(_Precio_W == null)
	        	    {
						_Precio_W = TearOff.Precio;
					}
					return _Precio_W;
				}
			}

			public AggregateParameter Marca
		    {
				get
		        {
					if(_Marca_W == null)
	        	    {
						_Marca_W = TearOff.Marca;
					}
					return _Marca_W;
				}
			}

			public AggregateParameter Nombre_distribuidor
		    {
				get
		        {
					if(_Nombre_distribuidor_W == null)
	        	    {
						_Nombre_distribuidor_W = TearOff.Nombre_distribuidor;
					}
					return _Nombre_distribuidor_W;
				}
			}

			public AggregateParameter Nombre_envio
		    {
				get
		        {
					if(_Nombre_envio_W == null)
	        	    {
						_Nombre_envio_W = TearOff.Nombre_envio;
					}
					return _Nombre_envio_W;
				}
			}

			public AggregateParameter Nombre_estado
		    {
				get
		        {
					if(_Nombre_estado_W == null)
	        	    {
						_Nombre_estado_W = TearOff.Nombre_estado;
					}
					return _Nombre_estado_W;
				}
			}

			public AggregateParameter No_orden
		    {
				get
		        {
					if(_No_orden_W == null)
	        	    {
						_No_orden_W = TearOff.No_orden;
					}
					return _No_orden_W;
				}
			}

			public AggregateParameter Fecha
		    {
				get
		        {
					if(_Fecha_W == null)
	        	    {
						_Fecha_W = TearOff.Fecha;
					}
					return _Fecha_W;
				}
			}

			public AggregateParameter Direccion_entrega
		    {
				get
		        {
					if(_Direccion_entrega_W == null)
	        	    {
						_Direccion_entrega_W = TearOff.Direccion_entrega;
					}
					return _Direccion_entrega_W;
				}
			}

			public AggregateParameter Comentario
		    {
				get
		        {
					if(_Comentario_W == null)
	        	    {
						_Comentario_W = TearOff.Comentario;
					}
					return _Comentario_W;
				}
			}

			public AggregateParameter Telefono
		    {
				get
		        {
					if(_Telefono_W == null)
	        	    {
						_Telefono_W = TearOff.Telefono;
					}
					return _Telefono_W;
				}
			}

			public AggregateParameter Email_notificacion
		    {
				get
		        {
					if(_Email_notificacion_W == null)
	        	    {
						_Email_notificacion_W = TearOff.Email_notificacion;
					}
					return _Email_notificacion_W;
				}
			}

			public AggregateParameter Destinatario
		    {
				get
		        {
					if(_Destinatario_W == null)
	        	    {
						_Destinatario_W = TearOff.Destinatario;
					}
					return _Destinatario_W;
				}
			}

			private AggregateParameter _Nombre_proveedor_W = null;
			private AggregateParameter _Cantidad_W = null;
			private AggregateParameter _Id_orden_W = null;
			private AggregateParameter _Id_producto_W = null;
			private AggregateParameter _Codigo_W = null;
			private AggregateParameter _Nombre_producto_W = null;
			private AggregateParameter _Precio_W = null;
			private AggregateParameter _Marca_W = null;
			private AggregateParameter _Nombre_distribuidor_W = null;
			private AggregateParameter _Nombre_envio_W = null;
			private AggregateParameter _Nombre_estado_W = null;
			private AggregateParameter _No_orden_W = null;
			private AggregateParameter _Fecha_W = null;
			private AggregateParameter _Direccion_entrega_W = null;
			private AggregateParameter _Comentario_W = null;
			private AggregateParameter _Telefono_W = null;
			private AggregateParameter _Email_notificacion_W = null;
			private AggregateParameter _Destinatario_W = null;

			public void AggregateClauseReset()
			{
				_Nombre_proveedor_W = null;
				_Cantidad_W = null;
				_Id_orden_W = null;
				_Id_producto_W = null;
				_Codigo_W = null;
				_Nombre_producto_W = null;
				_Precio_W = null;
				_Marca_W = null;
				_Nombre_distribuidor_W = null;
				_Nombre_envio_W = null;
				_Nombre_estado_W = null;
				_No_orden_W = null;
				_Fecha_W = null;
				_Direccion_entrega_W = null;
				_Comentario_W = null;
				_Telefono_W = null;
				_Email_notificacion_W = null;
				_Destinatario_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
			return null;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
			return null;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
			return null;
		}
	}
}
