
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using DALayer;

namespace BLLayer
{
	public class Distribuidor : _Distribuidor
	{
		public Distribuidor()
		{
		
		}
	}
}
