
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DALayer
{
	public abstract class _Estado_orden : SqlClientEntity
	{
		public _Estado_orden()
		{
			this.QuerySource = "Estado_orden";
			this.MappingName = "Estado_orden";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_Estado_ordenLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id_estado)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id_estado, Id_estado);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_Estado_ordenLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id_estado
			{
				get
				{
					return new SqlParameter("@Id_estado", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Nombre_estado
			{
				get
				{
					return new SqlParameter("@Nombre_estado", SqlDbType.VarChar, 50);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id_estado = "id_estado";
            public const string Nombre_estado = "nombre_estado";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id_estado] = _Estado_orden.PropertyNames.Id_estado;
					ht[Nombre_estado] = _Estado_orden.PropertyNames.Nombre_estado;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id_estado = "Id_estado";
            public const string Nombre_estado = "Nombre_estado";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id_estado] = _Estado_orden.ColumnNames.Id_estado;
					ht[Nombre_estado] = _Estado_orden.ColumnNames.Nombre_estado;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id_estado = "s_Id_estado";
            public const string Nombre_estado = "s_Nombre_estado";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id_estado
	    {
			get
	        {
				return base.Getint(ColumnNames.Id_estado);
			}
			set
	        {
				base.Setint(ColumnNames.Id_estado, value);
			}
		}

		public virtual string Nombre_estado
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nombre_estado);
			}
			set
	        {
				base.Setstring(ColumnNames.Nombre_estado, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id_estado
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id_estado) ? string.Empty : base.GetintAsString(ColumnNames.Id_estado);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id_estado);
				else
					this.Id_estado = base.SetintAsString(ColumnNames.Id_estado, value);
			}
		}

		public virtual string s_Nombre_estado
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nombre_estado) ? string.Empty : base.GetstringAsString(ColumnNames.Nombre_estado);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nombre_estado);
				else
					this.Nombre_estado = base.SetstringAsString(ColumnNames.Nombre_estado, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id_estado
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id_estado, Parameters.Id_estado);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nombre_estado
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nombre_estado, Parameters.Nombre_estado);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id_estado
		    {
				get
		        {
					if(_Id_estado_W == null)
	        	    {
						_Id_estado_W = TearOff.Id_estado;
					}
					return _Id_estado_W;
				}
			}

			public WhereParameter Nombre_estado
		    {
				get
		        {
					if(_Nombre_estado_W == null)
	        	    {
						_Nombre_estado_W = TearOff.Nombre_estado;
					}
					return _Nombre_estado_W;
				}
			}

			private WhereParameter _Id_estado_W = null;
			private WhereParameter _Nombre_estado_W = null;

			public void WhereClauseReset()
			{
				_Id_estado_W = null;
				_Nombre_estado_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id_estado
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id_estado, Parameters.Id_estado);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nombre_estado
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nombre_estado, Parameters.Nombre_estado);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id_estado
		    {
				get
		        {
					if(_Id_estado_W == null)
	        	    {
						_Id_estado_W = TearOff.Id_estado;
					}
					return _Id_estado_W;
				}
			}

			public AggregateParameter Nombre_estado
		    {
				get
		        {
					if(_Nombre_estado_W == null)
	        	    {
						_Nombre_estado_W = TearOff.Nombre_estado;
					}
					return _Nombre_estado_W;
				}
			}

			private AggregateParameter _Id_estado_W = null;
			private AggregateParameter _Nombre_estado_W = null;

			public void AggregateClauseReset()
			{
				_Id_estado_W = null;
				_Nombre_estado_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_Estado_ordenInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id_estado.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_Estado_ordenUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_Estado_ordenDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id_estado);
			p.SourceColumn = ColumnNames.Id_estado;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id_estado);
			p.SourceColumn = ColumnNames.Id_estado;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Nombre_estado);
			p.SourceColumn = ColumnNames.Nombre_estado;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
