
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using DALayer;

namespace BLLayer
{
	public class Estado_orden : _Estado_orden
	{
		public Estado_orden()
		{
		
		}
	}
}
