
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using DALayer;

namespace BLLayer
{
	public class Usuario : _Usuario
	{
		public Usuario()
		{
		
		}

        public bool validate(string login, string pasword)
        {
            this.LoadByLogin(login);
            return (this.RowCount > 0 && this.Password == pasword);
        }

        public void LoadByLogin(string login)
        {
            this.Where.WhereClauseReset();
            this.Where.Login.Value = login;
            this.Where.Login.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            this.Query.Load();
        }
        public bool ExistsUser(string login) 
        {
            LoadByLogin(login);
            return(this.RowCount>0);        
        }

        public void InsertAdmin(string nombre, string login, string password)
        {
            Insert(nombre, login, password, 1);
        }
        public bool Insert(string nombre, string login, string password, int id_role)
        {
            if (ExistsUser(login))
                return false;
            this.AddNew();
            this.Nombre = nombre;
            this.Login = login;
            this.Password = password;
            this.Id_role = id_role;
            this.Save();
            return true;
        }
	}
}
